spring.application.name=movietracker
spring.h2.console.enabled=false
spring.datasource.url=jdbc:h2:file:~/movietrackerdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# OAuth2 Client Configuration for GitHub
spring.security.oauth2.client.registration.github.clientId=${github-client-id}
spring.security.oauth2.client.registration.github.clientSecret=${github-client-secret}
spring.security.oauth2.client.registration.github.scope=read:user,user:email